### ISSUE TITLE
Update Webpage

### ISSUE THREAD

**Issue by sten2lu** [HeidelbergAI/website#4]
## ToDos
- [x] Add Helmholtz Imaging and IML Logos to `img/`
- [x] Update Landing Page (Count Meetup People and Remove Slack)
- [x] Add Gregor and Carsten as executives (about)
- [x] Move Jens to Program Comittee (about)
- [ ] Add HI and IML Logos (about)
